name: Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable_terraform_pipeline.yml
    with:
      branch: ${{ github.ref_name }}
      aws-access-key-id-dev: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
      aws-secret-access-key-dev: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
      aws-access-key-id-prod: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
      aws-secret-access-key-prod: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
      aws-ecr-repository-name: boilerplate-dev-api
