---
name: Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    uses: ./.github/workflows/reusable_terraform_pipeline.yml
    with:
      aws-ecr-repository-name: boilerplate-${{ github.ref_name }}-api
      branch: ${{ github.ref_name }}
      application_path: ../../typeorm-express-typescript
    secrets: inherit
