---
name: Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    uses: ./.github/workflows/reusable_terraform_pipeline.yml
    with:
      aws-ecr-repository-name: boilerplate-api
      application_path: ../../typeorm-express-typescript
    secrets: inherit
